### ISSUE TITLE
NoClipsFound exception

### ISSUE THREAD

**Issue by romek-codes** [offish/twitchtube#101]
I receive this error when trying to run TwitchTube, just 3 weeks ago it worked fine, and i also checked and it should have more than enough clips to work with.
```
Traceback (most recent call last):
  File "/home/romek/yt-automation/twitch_main.py", line 80, in <module>
    make_video(**parameters)
  File "/home/romek/yt-automation/twitchtube/video.py", line 138, in make_video
    raise NoClipsFound("Did not find any clips")
twitchtube.exceptions.NoClipsFound: Did not find any clips
```
This is 2 things in my config that i think are relevant, the video only needs to be 4 minutes and from one of the most popular and active "Games" on twitch so i think the problem isnt really that it couldn't find any clips.
```
VIDEO_LENGTH = 4  # Minimum video length in minutes (doesn't always work)
DATA = ["g Just Chatting"]
```
Could someone point me in a direction on what else i might be missing?

**Comment by ZMil** [comment]
Regen your token

https://github.com/offish/twitchtube#creating-your-twitch-application
