### ISSUE TITLE
Error uploading on Youtube

### ISSUE THREAD

**Issue by habibi92** [offish/twitchtube#102]
Hi,
Since this morning i'm trying to use this bot for uploading videos,
I can get clips/generate video, but i have an error when uploading on youtube

Traceback (most recent call last):
  File "/home/ubuntu/Desktop/Twitch-21jc/Mano/mano.py", line 8, in <module>
    make_video(
  File "/home/ubuntu/Desktop/Twitch-21jc/Mano/twitchtube/video.py", line 203, in make_video
    upload = Upload("/home/ubuntu/.mozilla/firefox/kter2kva.Selenium", "geckodriver", sleep, headless,
  File "/home/ubuntu/Desktop/Twitch-21jc/Mano/venv/lib/python3.8/site-packages/opplast/upload.py", line 34, in __init__
    self.driver = webdriver.Firefox(
  File "/home/ubuntu/Desktop/Twitch-21jc/Mano/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/ubuntu/Desktop/Twitch-21jc/Mano/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/Desktop/Twitch-21jc/Mano/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/Desktop/Twitch-21jc/Mano/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/Desktop/Twitch-21jc/Mano/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 127

How can i fix it? Trying to update the requirements but with no success

**Comment by akumathedyn123** [comment]
@habibi92  try using chrome driver. hoe many errors are you going to handle????
