### ISSUE TITLE
Heelp!!

### ISSUE THREAD

**Issue by DanielRuizSalvador** [offish/twitchtube#104]
Hello, I am creating a project with twitchtube to be able to download the best clips of the week from the Spanish streamers that I indicate. The thing is that I have tried with channels like xqcOW and it does extract some clips for me but with Spanish channels like elxokas, illojuan or ibai not. I don’t know if it’s because they have fewer visits or what the criterion is for not detecting them. I leave my project files at the following link: https://github.com/DanielRuizSalvador/twitchtube-

the error is this:

twitchtube | 10:28:36 - info: You're running the latest version of twitchtube at 1.6.6
twitchtube | 10:28:37 - info: You're running the latest version of opplast at 1.0.14
twitchtube | 10:28:37 - info: Going to make video featuring 2 streamers/games, that will end up being ~255.0 seconds long
twitchtube | 10:28:37 - info: Getting clips for channel elxokas
twitchtube | 10:28:38 - info: Getting clips for channel auronplay
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\python\MONEY\twitchtube-master\main.py", line 80, in <module>
    make_video(**parameters)
  File "C:\Users\Usuario\Desktop\python\MONEY\twitchtube-master\twitchtube\video.py", line 138, in make_video
    raise NoClipsFound("Did not find any clips")
twitchtube.exceptions.NoClipsFound: Did not find any clips

**Comment by imoliveira404** [comment]
The application seems not working any more

**Comment by akumathedyn123** [comment]
@DanielRuizSalvador what is the algorithm of your project. um like what are you using to detect best clip???? most view, playlist, keywords etc?????
