### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by saeedygujjar** [offish/twitchtube#18]
~/twitch $ python main.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/twitch/main.py", line 9, in <module>
    from twitchtube.config import *
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
PermissionError: [Errno 13] Permission denied: '/data/data/com.termux/files/home/twitch/twitchtube/config.py'
~/twitch $

**Comment by saeedygujjar** [comment]
![Screenshot_20210102-134442](https://user-images.githubusercontent.com/76161725/103456638-b790f000-4d00-11eb-93e1-da13e383a7a7.png)
