### ISSUE TITLE
Can't upload to youtube 

### ISSUE THREAD

**Issue by Zendek7** [offish/twitchtube#32]
The clips downloaded fine but it does not upload to youtube even with the firefox profile
> 
Traceback (most recent call last):
  File "C:\Users\Zendek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zendek\Desktop\twitchtube-master\main.py", line 55, in <module>
    upload = Upload(ROOT_PROFILE_PATH, SLEEP, HEADLESS, DEBUG)
  File "C:\Users\Zendek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\opplast\upload.py", line 22, in __init__
    self.driver = webdriver.Firefox(firefox_profile=profile, options=options)
  File "C:\Users\Zendek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Zendek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
>

**Comment by offish** [comment]
You need to add geckodriver to your PATH. Going to add this to the README in the next update.

**Comment by lvp11** [comment]
Having the same issue, already added geckodriver to PATH.

**Comment by GermanJesus-lul** [comment]
> Having the same issue, already added geckodriver to PATH.

error messages?

**Comment by lvp11** [comment]
> > Having the same issue, already added geckodriver to PATH.
> 
> error messages?

Same message as the OP

**Comment by offish** [comment]
If you type `geckodriver --version` and you get the issue above, it has not been added to PATH.
