### ISSUE TITLE
[Error] Could not find 'clips' in response

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [offish/twitchtube#46]
Hi, just updated to the new version and i'm getting this error when i want to make a new video, here is the error

```
C:\Users\MyUser\Desktop\twitchtube> python main.py "c mychannel, c friend1channel, c friend2channel, c friend3channel, c friend4channel" --duration 10.5 --resolution 1080 1920
twitchtube | 17:45:27 - info: Running twitchtube at v1.6.0
twitchtube | 17:45:27 - info: Starting to make video with 5 streamers/games
Traceback (most recent call last):
  File "C:\Users\User\Desktop\twitchtube\main.py", line 82, in <module>
    make_video(**parameters)
  File "C:\Users\User\Desktop\twitchtube\twitchtube\video.py", line 91, in make_video
    new_clips, new_ids = get_clips(
  File "C:\Users\User\Desktop\twitchtube\twitchtube\clips.py", line 128, in get_clips
    raise WrongKrakenResponse(f"Could not find 'clips' in response. {response}")
twitchtube.exceptions.WrongKrakenResponse: Could not find 'clips' in response. {'clips': [], '_cursor': ''}
```

**Comment by offish** [comment]
This might be because there are no clips in the given period. You can add `--period "week"` and see if it works then. What are the channels and the period you are using now?

**Comment by offish** [comment]
Does updating to v1.6.1 fix this issue?

**Comment by TomAvecLeVdsl** [comment]
Nope ... but seems to go futher

```
>python main.py "c mychannel, c friend1channel, c friend2channel, c friend3channel, c friend4channel" --duration 10.5 --resolution 1080 1920 --period "week"
twitchtube | 18:29:40 - info: You're running the latest version of twitchtube at 1.6.1
twitchtube | 18:29:41 - info: You're running the latest version of opplast at 1.0.6
twitchtube | 18:29:41 - info: Going to make video featuring 5 streamers/games, that will end up being ~126.0 seconds long
Traceback (most recent call last):
  File "C:\Users\User\Desktop\twitchtube-1.6.1\main.py", line 76, in <module>
    make_video(**parameters)
  File "C:\Users\User\Desktop\twitchtube-1.6.1\twitchtube\video.py", line 120, in make_video
    new_clips, new_ids = get_clips(
  File "C:\Users\User\Desktop\twitchtube-1.6.1\twitchtube\clips.py", line 131, in get_clips
    raise WrongKrakenResponse(f"Could not find 'clips' in response. {response}")
twitchtube.exceptions.WrongKrakenResponse: Could not find 'clips' in response. {'clips': [], '_cursor': ''}
```

**Comment by offish** [comment]
Have you specified language in the config? Which channels are you trying to get?

**Comment by TomAvecLeVdsl** [comment]
Language specified, twitch client id & oauth too
Ok so tryed with only one streamler that have clips, it works, it seems that the script doesen't have a if there is no clip skip the channel kind of thing

**Comment by offish** [comment]
Nope, will be fixed in a later update.

**Comment by TomAvecLeVdsl** [comment]
ok :) thanks for your help, i'l wait till this update :)
