### ISSUE TITLE
FileNotFoundError: [WinError 2] The specified file is not found

### ISSUE THREAD

**Issue by jeanchok** [offish/twitchtube#49]
Hello,
Just after the video is done recording ("twitchtube | 11:26:13 - info: Video is done rendering!") I have this error poping in my command prompt: 
`Traceback (most recent call last):
  File "C:\Users\Narvalo V2\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Narvalo V2\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Narvalo V2\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The specified file is not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BOT Twitch\V2\twitchtube-master\main.py", line 76, in <module>
    make_video(**parameters)
  File "D:\BOT Twitch\V2\twitchtube-master\twitchtube\video.py", line 173, in make_video
    upload = Upload(profile_path, sleep, headless, debug)
  File "C:\Users\Narvalo V2\AppData\Local\Programs\Python\Python39\lib\site-packages\opplast\upload.py", line 24, in __init__
    self.driver = webdriver.Firefox(firefox_profile=profile, options=options)
  File "C:\Users\Narvalo V2\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Narvalo V2\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.`

It stops the program before uploading on Youtube and I can't find the solution. Do you have any idea?

**Comment by offish** [comment]
You need to add geckodriver to PATH
