### ISSUE TITLE
Issues on Win 10

### ISSUE THREAD

**Issue by zeak6464** [offish/twitchtube#72]
```
Python 3.0 (r30:67507, Dec  3 2008, 19:44:23) [MSC v.1500 64 bit (AMD64)] on win32
IDLE 3.0      ==== No Subprocess ====
>>> 
Traceback (most recent call last):
  File "twitchtube-master\example.py", line 1, in <module>
    from twitchtube.video import make_video
  File "\twitchtube\video.py", line 83
    f"You're running an old version of {project}, installed: {version}, current: {current}"
                                                                                          ^
SyntaxError: invalid syntax
>>> 
```

**Comment by offish** [comment]
You're running Python 3.0 from 2008, update Python to 3.7 or later and you won't run into this.

**Comment by zeak6464** [comment]
in the main i had to add 

"from argparse import ArgumentParser" in order to make it work as well

and i changed this line as well "parser = ArgumentParser(description="")"
