### ISSUE TITLE
Connection error at home, but works at the library

### ISSUE THREAD

**Issue by DevJChen** [offish/twitchtube#91]
Whenever I go to the library and run this program, I get no errors when downloading the clips. However, when I run this program at my house, I can never seem to download one clip. I am not sure how to fix such an issue. I do not want to go to the library every time I want to run this program. Do you have any ideas on how to fix this? This is the error that is produced.

```
Traceback (most recent call last):
  File "D:/john/Pycharm Projects/twitchtube-master/example.py", line 9, in <module>
    make_video(
  File "D:\john\Pycharm Projects\twitchtube-master\twitchtube\video.py", line 143, in make_video
    names += download_clips(batch, path, oauth_token, client_id)
  File "D:\john\Pycharm Projects\twitchtube-master\twitchtube\clips.py", line 186, in download_clips
    download_clip(value["url"], path, oauth_token, client_id)
  File "D:\john\Pycharm Projects\twitchtube-master\twitchtube\clips.py", line 77, in download_clip
    urllib.request.urlretrieve(mp4_url, output_path, reporthook=get_progress)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 276, in urlretrieve
    block = fp.read(bs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by DevJChen** [comment]
@offish

**Comment by OwOHamper** [comment]
Error is most likely happening because of the library internet. Maybe they are not allowing uploading huge files or videos to youtube so they are closing your connection with youtube service.
